openapi: 3.0.0
info:
  version: 1.0.0
  title: Gateway Service API
  description: リソースをBackend Serviceに問い合わせます。

servers:
  - url: https://localhost:8080

paths:
  /resources:
    get:
      description: リソース一覧の取得を依頼します。
      responses:
        '200':
          description: 正常に取得できた場合。
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Resource'
              example:
                - id: 1
                  name: hainet
                - id: 2
                  name: kujaku

    post:
      description: リソースの登録を依頼します。
      requestBody:
        required: true
        content:
          application/json;charset=utf-8:
            schema:
              $ref: '#/components/schemas/Resource'
            example:
              name: hainet
      responses:
        '201':
          description: 正常に登録できた場合。
          headers:
            Location:
              $ref: '#/components/headers/Location'
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/Resource'
              example:
                id: 1
                name: hainet

  /resources/{id}:
    get:
      description: 指定したリソースの取得を依頼します。
      parameters:
        - $ref: '#/components/parameters/Id'
      responses:
        '200':
          description: 正常に取得できた場合。
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/Resource'
              example:
                id: 1
                name: hainet

    put:
      description: 指定したリソースの更新を依頼します。
      parameters:
        - $ref: '#/components/parameters/Id'
      requestBody:
        required: true
        content:
          application/json;charset=utf-8:
            schema:
              $ref: '#/components/schemas/Resource'
            example:
              name: hainet
      responses:
        '201':
          description: 新規にリソースが登録された場合。
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/Resource'
              example:
                id: 1
                name: hainet
        '204':
          description: 正常に更新できた場合。

    delete:
      description: 指定したリソースの削除を依頼します。
      parameters:
        - $ref: '#/components/parameters/Id'
      responses:
        '204':
          description: 正常に削除できた場合。

components:
  schemas:
    Resource:
      description: リソースを示します。
      type: object
      required:
        - name
      properties:
        id:
          type: integer
        name:
          type: string
    Message:
      description: 操作の結果を示します。
      type: object
      required:
        - message
      properties:
        message:
          type: string

  headers:
    Location:
      description: 登録されたリソースの場所を示します。
      schema:
        type: string

  parameters:
    Id:
      description: リソースのIDを指定します。
      name: id
      in: path
      required: true
      schema:
        type: string
      example: 1
